### ISSUE TITLE
Trying to get resque-clojure to run as its own process

### ISSUE THREAD

**Issue by newfoundresearch** [jxa/resque-clojure#2]
I am trying to get resque-clojure to run as its own process and am having some trouble.  For example:

```
(ns my-project.resque-agent
     (:require [resque-clojure.core :as resque]))

(resque/configure {:host (or (System/getenv "REDIS_HOST") "localhost")
               :port (or (System/getenv "REDIS_PORT") 6379)
               :poll-interval 1000
               :max-workers 10})

(defn -main []
     (resque/start ["workqueue"]))
```

Then I try to run it with:

> lein run -m my-project.resque-agent

To which I get:

```
IllegalArgumentException No matching ctor found for class redis.clients.jedis.JedisPool  clojure.lang.Reflector.invokeConstructor (Reflector.java:186)
```

The trouble seems to be in calling resque/start from within another function; I get the same error on the repl whenever I wrap resque/start in a function.  

What I am trying to achieve is the ability to launch multiple workers, powered by lein, using the same code.  What am I doing wrong?

Thanks!

**Comment by newfoundresearch** [comment]
More detail:

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching ctor found for class redis.clients.jedis.JedisPool
at clojure.lang.Reflector.invokeConstructor(Reflector.java:186)
at resque_clojure.redis$init_pool$fn__40.invoke(redis.clj:18)
at clojure.lang.AFn.call(AFn.java:18)
at clojure.lang.LockingTransaction.run(LockingTransaction.java:263)
at clojure.lang.LockingTransaction.runInTransaction(LockingTransaction.java:231)
at resque_clojure.redis$init_pool.invoke(redis.clj:16)
at resque_clojure.redis$sadd.invoke(redis.clj:64)
at resque_clojure.resque$register.invoke(resque.clj:37)
at resque_clojure.supervisor$listen_to.invoke(supervisor.clj:74)
at resque_clojure.supervisor$start.invoke(supervisor.clj:22)
at resque_clojure.core$start.invoke(core.clj:31)
```

**Comment by jxa** [comment]
Hi Corey,

When I create an example project with the same code the server starts without warning or error. I'm also able to wrap resque/start in a function at the repl without issue. Do you have any other connections to redis open when you lein run? Maybe in the repl? That isn't necessarily a problem, just trying to find out if there's more to it than the code you posted.

What versions of clojure and lein are you using? I tested with clojure 1.3.0 and lein 1.6.2

**Comment by newfoundresearch** [comment]
clojure 1.3.0, lein 1.6.2.

Here are my exact steps:

> lein new resque-test

I let project.clj look like:

```
(defproject resque-test "1.0.0-SNAPSHOT"
    :description "FIXME: write description"
    :dependencies [[org.clojure/clojure "1.3.0"]
                                [resque-clojure "0.2.0"]])
```

> lein deps

Then src/resque_test/core.clj looks like:

```
(ns resque-test.core
    (:require [resque-clojure.core :as resque]))

(resque/configure {:host (or (System/getenv "REDIS_HOST") "localhost")
                           :port (or (System/getenv "REDIS_PORT") 6379)
                           :poll-interval 1000
                           :max-workers 10})

(defn -main []
    (resque/start ["testqueue"]))
```

Then I run,

> lein run -m resque-test.core

And I get,

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching ctor found for class redis.clients.jedis.JedisPool
at clojure.lang.Reflector.invokeConstructor(Reflector.java:186)
at resque_clojure.redis$init_pool$fn__40.invoke(redis.clj:18)
at clojure.lang.AFn.call(AFn.java:18)
at clojure.lang.LockingTransaction.run(LockingTransaction.java:263)
at clojure.lang.LockingTransaction.runInTransaction(LockingTransaction.java:231)
at resque_clojure.redis$init_pool.invoke(redis.clj:16)
at resque_clojure.redis$sadd.invoke(redis.clj:64)
at resque_clojure.resque$register.invoke(resque.clj:37)
at resque_clojure.supervisor$listen_to.invoke(supervisor.clj:74)
at resque_clojure.supervisor$start.invoke(supervisor.clj:22)
at resque_clojure.core$start.invoke(core.clj:31)
at resque_test.core$_main.invoke(core.clj:11)
at clojure.lang.Var.invoke(Var.java:397)
at user$eval390.invoke(NO_SOURCE_FILE:1)
at clojure.lang.Compiler.eval(Compiler.java:6465)
at clojure.lang.Compiler.eval(Compiler.java:6455)
at clojure.lang.Compiler.eval(Compiler.java:6431)
at clojure.core$eval.invoke(core.clj:2795)
at clojure.main$eval_opt.invoke(main.clj:296)
at clojure.main$initialize.invoke(main.clj:315)
at clojure.main$null_opt.invoke(main.clj:348)
at clojure.main$main.doInvoke(main.clj:426)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at clojure.lang.Var.invoke(Var.java:405)
at clojure.lang.AFn.applyToHelper(AFn.java:163)
at clojure.lang.Var.applyTo(Var.java:518)
at clojure.main.main(main.java:37)
```

As far as I can tell, no other connections to redis when I run the code.  

Really appreciate the help.  I have a "work-around" currently using a lein plugin (lein-exec) to run the file as a script, but would love a full-fledged understanding as to why this doesn't work.

Don't know if it is helpful at all, but I am on Mac OS X 10.7.2 with redis version 2.4.3.

Thanks again.

**Comment by jxa** [comment]
If you specified a REDIS_PORT in your environment, (System/getenv "REDIS_PORT") would return a string, which is the wrong type for the JedisPool constructor. Just use (Integer/parseInt port-num) to convert it.
I'll consider doing the type conversion in a future version of the library.

**Comment by newfoundresearch** [comment]
Wow, that is horribly embarrassing.  Thanks so much for the help!
